### ISSUE TITLE
How is it use in React?

### ISSUE THREAD

**Issue by BigFaceMaster** [e-oj/Magic-Grid#7]

**Comment by e-oj** [comment]
You can also integrate it by creating a Magic Grid instance after the dom components have loaded. I haven't used react but here's a <b>[Vue.js example](https://github.com/e-oj/Gremlin/blob/master/public/src/components/site/collection/collection.vue#L83)<b>.

**Comment by BigFaceMaster** [comment]
Yes, but I think the react version is better for react.

**Comment by e-oj** [comment]
@BigFaceMaster Yeah I'd like a React version. I'll leave this issue open till you're done. Post back here when its ready so I'll add it to the readme. 

Merry Christmas 🎅

**Comment by BigFaceMaster** [comment]
OK, I'll tell you when I finish it. Merry Christmas~~~

**Comment by IniZio** [comment]
Porting to React at https://github.com/IniZio/React-Magic-Grid which basically mirrors https://github.com/imlinus/Vue-Magic-Grid. But I am not sure if using this way of actually importing `magic-grid` and instantiating it at `componentDidMount` is better :thinking:

**Comment by e-oj** [comment]
@IniZio It's hard to say which method is better. Some like the plain JS approach while others might prefer a component that's built for their frontend framework. It's best to have both options available so everyone is covered.

A few of the functions have changed since @imlinus made the Vue.js port. I've modified the setup and positionItems functions to increase efficiency and the getMax utility function has been removed completely. Update your functions to match the [updated functions](https://github.com/e-oj/Magic-Grid/blob/master/src/index.js). @imlinus, you should do the same for vue-magic-grid. 

Thanks a lot for contributing guys, I really appreciate it. 👍 👍

**Comment by e-oj** [comment]
> Nearly all of the logic can be reused if container selector part is refactored.

Refactored how?

**Comment by IniZio** [comment]
Someone took the name `react-magic-grid` though, using `magic-grid-react` instead for now :/

**Comment by imlinus** [comment]
I'll take a look at the code sometime later this week, today I'm too hungover 😁🖖

Happy new year lads ❤

**Comment by e-oj** [comment]
@IniZio I've added your repo to the readme. Try to get the code up to date though.

**Comment by IniZio** [comment]
Update React version to use magic-grid as peerDependencies to reuse almost all of its code :)
